cargo-features = ["resolver"]

[workspace]
resolver = "2"
members = [
    "nrf-softdevice",
    "nrf-softdevice-mbr",
    "nrf-softdevice-s112",
    "nrf-softdevice-s113",
    "nrf-softdevice-s122",
    "nrf-softdevice-s132",
    "nrf-softdevice-s140",
    "nrf-softdevice-macro",

    "examples",
    "nrf-softdevice-defmt-rtt",
]

exclude = [
    "nrf-softdevice-gen"
]

[patch.crates-io]
#embassy = { git = "https://github.com/embassy-rs/embassy" }
#embassy-nrf = { git = "https://github.com/embassy-rs/embassy" }
#embassy-macros = { git = "https://github.com/embassy-rs/embassy" }
#embassy-traits = { git = "https://github.com/embassy-rs/embassy" }
embassy = { path = "../embassy/embassy" }
embassy-nrf = { path = "../embassy/embassy-nrf" }
embassy-macros = { path = "../embassy/embassy-macros" }
embassy-traits = { path = "../embassy/embassy-traits" }

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = "fat"
opt-level = 's'
overflow-checks = false

[profile.release.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false
