[package]
authors = ["The Knurling-rs developers"]
categories = ["embedded", "no-std"]
description = "Transmit defmt log messages over the RTT (Real-Time Transfer) protocol"
edition = "2018"
keywords = ["knurling", "defmt", "defmt-transport"]
license = "MIT OR Apache-2.0"
name = "nrf-softdevice-defmt-rtt"
readme = "README.md"
repository = "https://github.com/knurling-rs/defmt"
version = "0.1.0"

[dependencies]
defmt = { version = "0.2.0" }
nrf-softdevice = { path = "../nrf-softdevice", version = "0.1.0" }
cortex-m = "0.6.4"
critical-section = { version = "0.2.1" }
